server:
  port: 10011
  #配置 结果压缩
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,image/png
    min-response-size: 50KB

spring:
  application:
    name: PROJECT-PLATFORM-ITEM
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    #password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 100
        min-idle: 20
        max-wait: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hall-marketing-ccb?useUnicode=true&amp&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      idle-timeout: 300000

    druid:
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username:
        # 登录密码
        login-password:

  #配置文件传输
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
  type-aliases-package: com.shop.entity

#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: countSql

logging:
  level:
    com: info
  file: log/catalina.out

#系统我的公共配置
my-configuration:
  # 静态资源存放路径(最后 要加“/”)
  static-locations: F:/home/project/widdom/staticFile/
  # 静态资源存放路径(最后 要加“/”)
  uploadPath: F:/home/project/widdom/staticFile/file/
  # 静态资源存放路径(最后 要加“/”)
  imagePath: /file/
  #项目缓存存储时间
  sessionTimeout: 7200
  #阿里信息
  accessKeyId:
  accessKeySecret:
  aliSmsSignName:
  aliSmsTemplateCode: SMS_174271428
  # 区域节点
  aliOssRegion: oss-cn-beijing
  # 访问节点
  aliOssEndpoint:
  aliOssBucketNameUser:
  aliOssAcsRamRole: acs:ram::1088928632484109:role/oss
  #验证码长度
  codeLength: 6
  baidu-ueditor-locations: F:/IDE/IDEA_JAVA/mzy_workspace/hall-marketing/hall-marketing-cloud-ccb/project-platform-item/config
